[package]
name = "kinglet"
version = "0.1.0"
edition = "2021"
authors = [ "Nelu Snegur <nelu@pulsarplanet.com>" ]
keywords = [ "kernel", "os", "arm" ]
license = "MIT"
readme = "README.md"
repository = "https://github.com/nelusnegur/kinglet"
include = [
  "src/**/*",
  "Cargo.toml",
  "LICENSE",
]

[dependencies]
