[package]
name = "kinglet_drivers"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
kinglet = { version = "0.0.1", path = "../klib", package = "kinglet_lib" }
